import type { BuildingDefinition } from '../model/content'

/** Every building occupies exactly one acre, so land is the master constraint. */
const ONE_ACRE = 1

export const BUILDING_DEFINITIONS: readonly BuildingDefinition[] = [
  {
    id: 'house',
    name: 'House',
    flavor: 'Four walls and a hearth. Raises the number of citizens your land can hold.',
    acreCost: ONE_ACRE,
    costs: { wood: 20, stone: 5 },
    baseConstructionSeconds: 8,
    workerSlotsPerBuilding: 0,
    effects: [{ kind: 'grantCapacity', capacityId: 'population', amountPerBuilding: 4 }],
  },
  {
    id: 'farm',
    name: 'Farm',
    flavor: 'Furrowed fields. Assign citizens to work them.',
    acreCost: ONE_ACRE,
    costs: { wood: 15, stone: 5 },
    baseConstructionSeconds: 10,
    workerSlotsPerBuilding: 3,
    workerRoleName: 'farmers',
    effects: [{ kind: 'produceResource', resourceId: 'food', amountPerWorkerPerSecond: 0.28 }],
  },
  {
    id: 'lumberCamp',
    name: 'Lumber Camp',
    flavor: 'Axes, sledges and a felling yard.',
    acreCost: ONE_ACRE,
    costs: { wood: 10, stone: 12 },
    baseConstructionSeconds: 10,
    workerSlotsPerBuilding: 3,
    workerRoleName: 'woodcutters',
    effects: [{ kind: 'produceResource', resourceId: 'wood', amountPerWorkerPerSecond: 0.28 }],
  },
  {
    id: 'quarry',
    name: 'Quarry',
    flavor: 'A worked face of rock and the dust that comes with it.',
    acreCost: ONE_ACRE,
    costs: { wood: 25, stone: 8 },
    baseConstructionSeconds: 12,
    workerSlotsPerBuilding: 3,
    workerRoleName: 'quarriers',
    effects: [{ kind: 'produceResource', resourceId: 'stone', amountPerWorkerPerSecond: 0.2 }],
  },
  {
    id: 'mine',
    name: 'Mine',
    flavor: 'A shaft driven after a vein of ore.',
    acreCost: ONE_ACRE,
    costs: { wood: 40, stone: 30 },
    baseConstructionSeconds: 16,
    workerSlotsPerBuilding: 3,
    workerRoleName: 'miners',
    effects: [{ kind: 'produceResource', resourceId: 'gold', amountPerWorkerPerSecond: 0.13 }],
  },
  {
    id: 'barracks',
    name: 'Barracks',
    flavor: 'Drill yard and bunks. Assigned citizens train and hold soldiers in readiness.',
    acreCost: ONE_ACRE,
    costs: { wood: 60, stone: 40, gold: 20 },
    baseConstructionSeconds: 20,
    workerSlotsPerBuilding: 2,
    workerRoleName: 'drill-masters',
    effects: [{ kind: 'grantCapacity', capacityId: 'army', amountPerWorker: 6 }],
  },
  {
    id: 'thievesGuild',
    name: "Thieves' Guild",
    flavor: 'A quiet door in a loud street. Assigned citizens run the network.',
    acreCost: ONE_ACRE,
    costs: { wood: 50, stone: 30, gold: 35 },
    baseConstructionSeconds: 20,
    workerSlotsPerBuilding: 2,
    workerRoleName: 'fences',
    effects: [{ kind: 'grantCapacity', capacityId: 'thieves', amountPerWorker: 3 }],
  },
  {
    id: 'temple',
    name: 'Temple',
    flavor: 'Twin altars to Hai and Yah. Assigned citizens study, and the circles answer.',
    acreCost: ONE_ACRE,
    costs: { wood: 80, stone: 60, gold: 40 },
    baseConstructionSeconds: 26,
    workerSlotsPerBuilding: 2,
    workerRoleName: 'priests',
    effects: [{ kind: 'generateMagicExperience', experiencePerWorkerPerSecond: 0.03 }],
  },
]
