import type { ConquestTargetDefinition } from '../model/content'

/** The only source of acres, so this ladder paces the whole game. */
export const CONQUEST_TARGET_DEFINITIONS: readonly ConquestTargetDefinition[] = [
  {
    id: 'hamlet',
    name: 'Outlying Hamlet',
    tier: 1,
    flavor: 'Eleven families and a fence. They will not hold.',
    requiredSoldiers: 6,
    defenseStrength: 6,
    acresGained: 3,
    plunder: { food: 60, wood: 40, stone: 20, gold: 15 },
    travelSeconds: 60,
    conquestLimit: 60,
  },
  {
    id: 'village',
    name: 'Riverside Village',
    tier: 2,
    flavor: 'A mill, a shrine, and men who have fought off raiders before.',
    requiredSoldiers: 25,
    defenseStrength: 34,
    acresGained: 8,
    plunder: { food: 300, wood: 220, stone: 140, gold: 120 },
    travelSeconds: 150,
    conquestLimit: 60,
  },
  {
    id: 'town',
    name: 'Walled Town',
    tier: 3,
    flavor: 'A ditch, a gate and a garrison that is paid on time.',
    requiredSoldiers: 90,
    defenseStrength: 145,
    acresGained: 22,
    plunder: { food: 1_800, wood: 1_500, stone: 1_200, gold: 1_400 },
    travelSeconds: 360,
    conquestLimit: 50,
  },
  {
    id: 'city',
    name: 'Free City',
    tier: 4,
    flavor: 'Towers, a standing watch, and a council that will not treat with you.',
    requiredSoldiers: 320,
    defenseStrength: 640,
    acresGained: 60,
    plunder: { food: 12_000, wood: 11_000, stone: 10_000, gold: 14_000 },
    travelSeconds: 900,
    conquestLimit: 40,
  },
  {
    id: 'capital',
    name: 'Rival Capital',
    tier: 5,
    flavor: 'A throne that has never been taken. Its army is professional.',
    requiredSoldiers: 1_100,
    defenseStrength: 2_600,
    acresGained: 160,
    plunder: { food: 90_000, wood: 85_000, stone: 80_000, gold: 120_000 },
    travelSeconds: 1_800,
    conquestLimit: 24,
  },
  {
    id: 'twinThrones',
    name: 'The Twin Thrones',
    tier: 6,
    flavor:
      'The seat where Hai and Yah are said to argue. Whoever holds it holds the world’s last free acres.',
    requiredSoldiers: 4_000,
    defenseStrength: 11_000,
    acresGained: 400,
    plunder: { food: 600_000, wood: 600_000, stone: 600_000, gold: 900_000 },
    travelSeconds: 3_600,
    conquestLimit: 8,
  },
]
