import type { UpgradeDefinition, UpgradeLineDefinition } from '../model/content'
import { RESOURCE_IDS } from '../model/ids'
import type { Modifier } from '../model/modifiers'

export const UPGRADE_LINE_DEFINITIONS: readonly UpgradeLineDefinition[] = [
  { id: 'housing', name: 'Housing', flavor: 'Better walls hold more people in the same acre.' },
  { id: 'farming', name: 'Farming', flavor: 'Tools and technique between you and famine.' },
  { id: 'woodcutting', name: 'Woodcutting', flavor: 'Sharper steel, fewer strokes.' },
  { id: 'quarrying', name: 'Quarrying', flavor: 'Splitting rock is a craft, not a labour.' },
  { id: 'mining', name: 'Mining', flavor: 'Deeper shafts, richer seams.' },
  { id: 'preservation', name: 'Preservation', flavor: 'Food that keeps is food you did not lose.' },
  { id: 'logistics', name: 'Logistics', flavor: 'Roads make every other improvement worth more.' },
  { id: 'military', name: 'Military', flavor: 'Drill, discipline and engines of war.' },
  { id: 'thievery', name: 'Thievery', flavor: 'The quiet trade, practised properly.' },
  { id: 'arcana', name: 'Arcana', flavor: 'Instruments and libraries for the circles.' },
  { id: 'gathering', name: 'Gathering', flavor: 'Your own two hands, better used.' },
  { id: 'fortification', name: 'Fortification', flavor: 'Endless small reinforcements. Repeatable.' },
  { id: 'bribery', name: 'Bribery', flavor: 'Coin in the right palm, again and again. Repeatable.' },
]

const allProductionModifiers = (multiplier: number): readonly Modifier[] =>
  RESOURCE_IDS.map((resourceId) => ({
    target: `production.${resourceId}` as const,
    operation: 'multiply' as const,
    value: multiplier,
  }))

export const UPGRADE_DEFINITIONS: readonly UpgradeDefinition[] = [
  {
    id: 'housing.timberFrames',
    lineId: 'housing',
    name: 'Timber Frames',
    flavor: 'A proper frame instead of lashed poles. Housing capacity +40%.',
    costs: { wood: 400, stone: 120 },
    requires: { buildingCounts: { house: 3 } },
    modifiers: [{ target: 'capacity.population', operation: 'multiply', value: 1.4 }],
  },
  {
    id: 'housing.stoneHouses',
    lineId: 'housing',
    name: 'Stone Houses',
    flavor: 'Cut stone, two storeys, a real roof. Housing capacity +60%.',
    costs: { wood: 2_500, stone: 4_000, gold: 800 },
    requires: { upgradeIds: ['housing.timberFrames'], buildingCounts: { house: 8 } },
    modifiers: [{ target: 'capacity.population', operation: 'multiply', value: 1.6 }],
  },
  {
    id: 'housing.manorHalls',
    lineId: 'housing',
    name: 'Manor Halls',
    flavor: 'Long halls that sleep whole families. Housing capacity +80%.',
    costs: { wood: 40_000, stone: 60_000, gold: 20_000 },
    requires: {
      upgradeIds: ['housing.stoneHouses'],
      buildingCounts: { house: 20 },
      conquestTierDefeated: 2,
    },
    modifiers: [{ target: 'capacity.population', operation: 'multiply', value: 1.8 }],
  },

  {
    id: 'farming.ironPlows',
    lineId: 'farming',
    name: 'Iron Plows',
    flavor: 'Iron cuts the sod the wooden share only bruised. Farms +30%.',
    costs: { wood: 300, gold: 150 },
    requires: { buildingCounts: { farm: 2 } },
    modifiers: [{ target: 'buildingOutput.farm', operation: 'multiply', value: 1.3 }],
  },
  {
    id: 'farming.cropRotation',
    lineId: 'farming',
    name: 'Crop Rotation',
    flavor: 'Rest a field and it pays you back. Farms +40%.',
    costs: { wood: 2_000, food: 3_000, gold: 1_200 },
    requires: { upgradeIds: ['farming.ironPlows'], buildingCounts: { farm: 5 } },
    modifiers: [{ target: 'buildingOutput.farm', operation: 'multiply', value: 1.4 }],
  },
  {
    id: 'farming.aqueducts',
    lineId: 'farming',
    name: 'Aqueducts',
    flavor: 'Water arrives whether or not it rains. Farms +50%.',
    costs: { stone: 45_000, wood: 20_000, gold: 15_000 },
    requires: { upgradeIds: ['farming.cropRotation'], buildingCounts: { farm: 12 } },
    modifiers: [{ target: 'buildingOutput.farm', operation: 'multiply', value: 1.5 }],
  },

  {
    id: 'woodcutting.bronzeAxes',
    lineId: 'woodcutting',
    name: 'Bronze Axes',
    flavor: 'Cast heads that keep an edge. Lumber camps +30%.',
    costs: { wood: 250, gold: 120 },
    requires: { buildingCounts: { lumberCamp: 2 } },
    modifiers: [{ target: 'buildingOutput.lumberCamp', operation: 'multiply', value: 1.3 }],
  },
  {
    id: 'woodcutting.steelAxes',
    lineId: 'woodcutting',
    name: 'Steel Axes',
    flavor: 'Half the strokes, twice the trees. Lumber camps +40%.',
    costs: { wood: 1_800, stone: 900, gold: 1_400 },
    requires: { upgradeIds: ['woodcutting.bronzeAxes'], buildingCounts: { lumberCamp: 5 } },
    modifiers: [{ target: 'buildingOutput.lumberCamp', operation: 'multiply', value: 1.4 }],
  },
  {
    id: 'woodcutting.whipsaws',
    lineId: 'woodcutting',
    name: 'Whipsaws',
    flavor: 'Two-man saws and a felling yard that never stops. Lumber camps +50%.',
    costs: { wood: 30_000, stone: 18_000, gold: 22_000 },
    requires: { upgradeIds: ['woodcutting.steelAxes'], buildingCounts: { lumberCamp: 12 } },
    modifiers: [{ target: 'buildingOutput.lumberCamp', operation: 'multiply', value: 1.5 }],
  },

  {
    id: 'quarrying.ironChisels',
    lineId: 'quarrying',
    name: 'Iron Chisels',
    flavor: 'Stone splits where you mark it. Quarries +30%.',
    costs: { wood: 200, gold: 180 },
    requires: { buildingCounts: { quarry: 2 } },
    modifiers: [{ target: 'buildingOutput.quarry', operation: 'multiply', value: 1.3 }],
  },
  {
    id: 'quarrying.wedgeAndFeather',
    lineId: 'quarrying',
    name: 'Wedge & Feather',
    flavor: 'A trick of iron that opens a face cleanly. Quarries +40%.',
    costs: { wood: 1_500, stone: 1_200, gold: 1_500 },
    requires: { upgradeIds: ['quarrying.ironChisels'], buildingCounts: { quarry: 5 } },
    modifiers: [{ target: 'buildingOutput.quarry', operation: 'multiply', value: 1.4 }],
  },
  {
    id: 'quarrying.cranes',
    lineId: 'quarrying',
    name: 'Treadwheel Cranes',
    flavor: 'Blocks leave the pit as fast as they are cut. Quarries +50%.',
    costs: { wood: 35_000, stone: 25_000, gold: 20_000 },
    requires: { upgradeIds: ['quarrying.wedgeAndFeather'], buildingCounts: { quarry: 12 } },
    modifiers: [{ target: 'buildingOutput.quarry', operation: 'multiply', value: 1.5 }],
  },

  {
    id: 'mining.ironPicks',
    lineId: 'mining',
    name: 'Iron Picks',
    flavor: 'Iron bites where bronze glances. Mines +30%.',
    costs: { wood: 400, stone: 300, gold: 200 },
    requires: { buildingCounts: { mine: 2 } },
    modifiers: [{ target: 'buildingOutput.mine', operation: 'multiply', value: 1.3 }],
  },
  {
    id: 'mining.steelPicks',
    lineId: 'mining',
    name: 'Steel Picks',
    flavor: 'Tempered heads and a smith to keep them. Mines +40%.',
    costs: { wood: 2_500, stone: 2_500, gold: 2_000 },
    requires: { upgradeIds: ['mining.ironPicks'], buildingCounts: { mine: 5 } },
    modifiers: [{ target: 'buildingOutput.mine', operation: 'multiply', value: 1.4 }],
  },
  {
    id: 'mining.blastingPowder',
    lineId: 'mining',
    name: 'Blasting Powder',
    flavor: 'A charge does in a heartbeat what a shift could not. Mines +60%.',
    costs: { wood: 40_000, stone: 40_000, gold: 35_000 },
    requires: {
      upgradeIds: ['mining.steelPicks'],
      buildingCounts: { mine: 12 },
      anyMagicCircleTier: 2,
    },
    modifiers: [{ target: 'buildingOutput.mine', operation: 'multiply', value: 1.6 }],
  },

  {
    id: 'preservation.rootCellars',
    lineId: 'preservation',
    name: 'Root Cellars',
    flavor: 'Cold earth keeps a harvest honest. Your people eat 10% less.',
    costs: { wood: 350, stone: 350 },
    requires: { buildingCounts: { farm: 3 } },
    modifiers: [{ target: 'consumption.food', operation: 'multiply', value: 0.9 }],
  },
  {
    id: 'preservation.granaries',
    lineId: 'preservation',
    name: 'Granaries',
    flavor: 'Raised floors, tight lids, no vermin. Your people eat a further 15% less.',
    costs: { wood: 3_000, stone: 3_000, gold: 1_000 },
    requires: { upgradeIds: ['preservation.rootCellars'], buildingCounts: { farm: 8 } },
    modifiers: [{ target: 'consumption.food', operation: 'multiply', value: 0.85 }],
  },
  {
    id: 'preservation.coldVaults',
    lineId: 'preservation',
    name: 'Cold Vaults',
    flavor: 'Ice cut in winter, kept all year. Your people eat a further 20% less.',
    costs: { stone: 50_000, wood: 25_000, gold: 25_000 },
    requires: {
      upgradeIds: ['preservation.granaries'],
      buildingCounts: { farm: 15 },
      anyMagicCircleTier: 3,
    },
    modifiers: [{ target: 'consumption.food', operation: 'multiply', value: 0.8 }],
  },

  {
    id: 'logistics.handcarts',
    lineId: 'logistics',
    name: 'Handcarts',
    flavor: 'Nobody should carry what a wheel can. All production +10%.',
    costs: { wood: 600, gold: 300 },
    requires: { buildingCounts: { house: 5 } },
    modifiers: allProductionModifiers(1.1),
  },
  {
    id: 'logistics.wagons',
    lineId: 'logistics',
    name: 'Wagons',
    flavor: 'Draught teams and axles. All production +15%, marches 15% faster.',
    costs: { wood: 5_000, stone: 2_000, gold: 3_500 },
    requires: { upgradeIds: ['logistics.handcarts'], buildingCounts: { house: 12 } },
    modifiers: [
      ...allProductionModifiers(1.15),
      { target: 'warfare.travelSpeed', operation: 'multiply', value: 1.15 },
      { target: 'warfare.returnSpeed', operation: 'multiply', value: 1.15 },
    ],
  },
  {
    id: 'logistics.pavedRoads',
    lineId: 'logistics',
    name: 'Paved Roads',
    flavor: 'Stone under every wheel in the realm. All production +20%, marches 25% faster.',
    costs: { stone: 80_000, wood: 40_000, gold: 40_000 },
    requires: {
      upgradeIds: ['logistics.wagons'],
      buildingCounts: { house: 25 },
      conquestTierDefeated: 3,
    },
    modifiers: [
      ...allProductionModifiers(1.2),
      { target: 'warfare.travelSpeed', operation: 'multiply', value: 1.25 },
      { target: 'warfare.returnSpeed', operation: 'multiply', value: 1.25 },
      { target: 'thievery.speed', operation: 'multiply', value: 1.25 },
    ],
  },

  {
    id: 'military.drillYards',
    lineId: 'military',
    name: 'Drill Yards',
    flavor: 'Soldiers who have done it before. Attack power +25%.',
    costs: { wood: 800, stone: 400, gold: 500 },
    requires: { buildingCounts: { barracks: 1 } },
    modifiers: [{ target: 'warfare.attackPower', operation: 'multiply', value: 1.25 }],
  },
  {
    id: 'military.standingArmy',
    lineId: 'military',
    name: 'Standing Army',
    flavor: 'Paid, housed, always ready. Attack power +35%, army capacity +20%.',
    costs: { wood: 6_000, stone: 3_000, gold: 6_000 },
    requires: {
      upgradeIds: ['military.drillYards'],
      buildingCounts: { barracks: 3 },
      conquestTierDefeated: 1,
    },
    modifiers: [
      { target: 'warfare.attackPower', operation: 'multiply', value: 1.35 },
      { target: 'capacity.army', operation: 'multiply', value: 1.2 },
    ],
  },
  {
    id: 'military.siegeEngines',
    lineId: 'military',
    name: 'Siege Engines',
    flavor: 'Walls stop being an argument. Attack power +60%, casualties −20%.',
    costs: { wood: 70_000, stone: 50_000, gold: 60_000 },
    requires: {
      upgradeIds: ['military.standingArmy'],
      buildingCounts: { barracks: 8 },
      conquestTierDefeated: 3,
    },
    modifiers: [
      { target: 'warfare.attackPower', operation: 'multiply', value: 1.6 },
      { target: 'warfare.casualtyRate', operation: 'multiply', value: 0.8 },
    ],
  },

  {
    id: 'thievery.lockpicks',
    lineId: 'thievery',
    name: 'Lockpicks',
    flavor: 'A set of picks and someone taught to use them. Heist success +20%.',
    costs: { wood: 400, gold: 600 },
    requires: { buildingCounts: { thievesGuild: 1 } },
    modifiers: [{ target: 'thievery.successChance', operation: 'multiply', value: 1.2 }],
  },
  {
    id: 'thievery.smokeBombs',
    lineId: 'thievery',
    name: 'Smoke Bombs',
    flavor: 'An exit is worth more than an entrance. Casualties −30%, loot +25%.',
    costs: { wood: 3_000, stone: 1_500, gold: 5_000 },
    requires: { upgradeIds: ['thievery.lockpicks'], buildingCounts: { thievesGuild: 3 } },
    modifiers: [
      { target: 'thievery.casualtyRate', operation: 'multiply', value: 0.7 },
      { target: 'thievery.loot', operation: 'multiply', value: 1.25 },
    ],
  },
  {
    id: 'thievery.guildNetwork',
    lineId: 'thievery',
    name: 'Guild Network',
    flavor: 'Eyes in every city you have not taken yet. Success +25%, loot +60%.',
    costs: { wood: 40_000, stone: 25_000, gold: 70_000 },
    requires: {
      upgradeIds: ['thievery.smokeBombs'],
      buildingCounts: { thievesGuild: 8 },
      anyMagicCircleTier: 3,
    },
    modifiers: [
      { target: 'thievery.successChance', operation: 'multiply', value: 1.25 },
      { target: 'thievery.loot', operation: 'multiply', value: 1.6 },
    ],
  },

  {
    id: 'arcana.scriptoria',
    lineId: 'arcana',
    name: 'Scriptoria',
    flavor: 'Someone finally wrote it down. Magical experience +30%.',
    costs: { wood: 900, stone: 600, gold: 700 },
    requires: { buildingCounts: { temple: 1 } },
    modifiers: [{ target: 'magic.experienceGain', operation: 'multiply', value: 1.3 }],
  },
  {
    id: 'arcana.astrolabes',
    lineId: 'arcana',
    name: 'Astrolabes',
    flavor: 'Hai and Yah measured against the stars. Experience +40%, mana pool +50%.',
    costs: { wood: 5_000, stone: 4_000, gold: 6_000 },
    requires: { upgradeIds: ['arcana.scriptoria'], buildingCounts: { temple: 3 } },
    modifiers: [
      { target: 'magic.experienceGain', operation: 'multiply', value: 1.4 },
      { target: 'magic.manaPool', operation: 'multiply', value: 1.5 },
      { target: 'magic.manaRegen', operation: 'multiply', value: 1.3 },
    ],
  },
  {
    id: 'arcana.leyLines',
    lineId: 'arcana',
    name: 'Ley Lines',
    flavor: 'The circles no longer wait on your temples. Experience +60%, mana pool doubled.',
    costs: { wood: 50_000, stone: 50_000, gold: 60_000 },
    requires: {
      upgradeIds: ['arcana.astrolabes'],
      buildingCounts: { temple: 8 },
      anyMagicCircleTier: 3,
    },
    modifiers: [
      { target: 'magic.experienceGain', operation: 'multiply', value: 1.6 },
      { target: 'magic.manaPool', operation: 'multiply', value: 2 },
      { target: 'magic.manaRegen', operation: 'multiply', value: 1.8 },
    ],
  },

  {
    id: 'gathering.callousedHands',
    lineId: 'gathering',
    name: 'Calloused Hands',
    flavor: 'You have done this a while now. Hand-gathering doubled.',
    costs: { wood: 40, stone: 20 },
    requires: {},
    modifiers: [{ target: 'manualGatherYield', operation: 'multiply', value: 2 }],
  },
  {
    id: 'gathering.practisedHands',
    lineId: 'gathering',
    name: 'Practised Hands',
    flavor: 'Fewer wasted motions. Hand-gathering tripled again.',
    costs: { wood: 500, stone: 400, gold: 100 },
    requires: { upgradeIds: ['gathering.callousedHands'] },
    modifiers: [{ target: 'manualGatherYield', operation: 'multiply', value: 3 }],
  },
  {
    id: 'gathering.masterGatherers',
    lineId: 'gathering',
    name: 'Master Gatherers',
    flavor: 'A crew that follows where you point. Hand-gathering ten times over.',
    costs: { wood: 8_000, stone: 6_000, gold: 4_000 },
    requires: { upgradeIds: ['gathering.practisedHands'], buildingCounts: { house: 10 } },
    modifiers: [{ target: 'manualGatherYield', operation: 'multiply', value: 10 }],
  },

  {
    id: 'fortification.reinforceWalls',
    lineId: 'fortification',
    name: 'Reinforce Walls',
    flavor: 'Another course of stone, another few soldiers home. Casualties −4% each time.',
    costs: { stone: 6_000, wood: 3_000, gold: 2_000 },
    requires: { buildingCounts: { barracks: 2 } },
    modifiers: [{ target: 'warfare.casualtyRate', operation: 'multiply', value: 0.96 }],
    repeatable: { maxPurchases: 25, costGrowth: 1.35 },
  },
  {
    id: 'bribery.guildBribes',
    lineId: 'bribery',
    name: 'Guild Bribes',
    flavor: 'Coin in the right palm. Heist success +3% each time, though no job is ever certain.',
    costs: { gold: 9_000 },
    requires: { buildingCounts: { thievesGuild: 2 } },
    modifiers: [{ target: 'thievery.successChance', operation: 'multiply', value: 1.03 }],
    repeatable: { maxPurchases: 12, costGrowth: 1.4 },
  },
]
